// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_yWftokt6lG3xMZWZt5TV2EHRkZY6pM',
    appId: '1:681443339119:web:f8c6b722a35c7ed2f1569a',
    messagingSenderId: '681443339119',
    projectId: 'invitationgen-7eb56',
    authDomain: 'invitationgen-7eb56.firebaseapp.com',
    storageBucket: 'invitationgen-7eb56.appspot.com',
    measurementId: 'G-CERF28B40G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLr-mmuWyrQaGBHWmHRgbDzPOhsuQLdU',
    appId: '1:681443339119:android:5fd939956689b991f1569a',
    messagingSenderId: '681443339119',
    projectId: 'invitationgen-7eb56',
    storageBucket: 'invitationgen-7eb56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJhzN9IPyBgmkZVEH6-GAOn1BOAH9kE1Y',
    appId: '1:681443339119:ios:758a44a1969e52d4f1569a',
    messagingSenderId: '681443339119',
    projectId: 'invitationgen-7eb56',
    storageBucket: 'invitationgen-7eb56.appspot.com',
    iosClientId: '681443339119-t5941pn6db75knk4e56p2f0mllfc05v0.apps.googleusercontent.com',
    iosBundleId: 'com.invitationgen.invitationgen',
  );

}